
server:
  port: 8090

logging.level.org.springframework.r2dbc: debug

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings:
    products-out-0:
      destination: products
      producer:
        required-groups: auditGroup

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest